export const componentLabels: Record<string, string> = {
  "el-input": "输入框",
  "el-select": "选择器",
  "el-radio": "单选框",
  "el-radio-group": "单选框组",
  "el-checkbox": "复选框",
  "el-checkbox-group": "复选框组",
  "el-switch": "开关",
  "el-slider": "滑块",
  "el-time-picker": "时间选择器",
  "el-date-picker": "日期选择器",
  "el-rate": "评分",
  "el-color-picker": "颜色选择器",
  "el-transfer": "穿梭框",
  "el-button": "按钮",
  "el-button-group": "按钮组",
  "el-table": "表格",
  "el-tag": "标签",
  "el-progress": "进度条",
  "el-tree": "树形控件",
  "el-pagination": "分页",
  "el-badge": "徽章",
  "el-avatar": "头像",
  "el-alert": "警告",
  "el-menu": "导航菜单",
  "el-tabs": "标签页",
  "el-breadcrumb": "面包屑",
  "el-dropdown": "下拉菜单",
  "el-steps": "步骤条",
  "el-dialog": "对话框",
  "el-tooltip": "文字提示",
  "el-popover": "弹出框",
  "el-card": "卡片",
  "el-carousel": "走马灯",
  "el-collapse": "折叠面板",
  "el-divider": "分割线",
  "el-image": "图片",
  "el-backtop": "回到顶部",
  "el-infinite-scroll": "无限滚动",
  "el-drawer": "抽屉",
  "el-timeline": "时间线"
};

export const getDefaultLabel = (componentType: string): string => {
  return componentLabels[componentType] || "新组件";
};
